# Available languages: eng (English), rus (Русский)
language: "eng"

# Distance at which the local message will be visible
local-chat-radius: 100

# The symbol for sending a message to the global chat.
# Example: "!your message"
global-chat-symbol: "!"

# Prefix for local and global chat 
# Example: "L | MEFRREEX: your message"
chat-prefix:
  local: "&l &aL &8|&r"
  global: "&l &cG &8|&r"
  spy: "&l &6SPY &8|&r"

# Message that there are no recipients
enable-no-recipients-message: true

# If enabled, only players with permission can write in local and global chat.
# Permissions: chatsplitter.chat.local, chatsplitter.chat.global
enable-permissions: false

# Plugin command
commands:
  # Local spy command
  spy:
    name: "localspy"
    description: "Local chat spy"
    aliases: ["lspy"]