# Distance at which the local message will be visible
radius: 100

# The symbol for sending a message to the global chat.
# Example: "!your message"
symbol: "!"

# Prefix for local and global chat 
# Example: "L | MEFRREEXX: your message" 
prefix:
  local: "§l §aL §8|§r"
  global: "§l §cG §8|§r"
  spy: "§l §6SPY §8|§r"

# If enabled, only players with permission can write in local and global chat.
# Permissions: splitchat.chat.local, splitchat.chat.global
enable-permissions: false