name: ${project.name}
version: ${project.version}
api: ["1.0.8"]
author: The Oni
description: ${project.description}
main: theoni.splitchat.Main

permissions:
  debugtool.use:
    default: op
  debugtool.about:
    default: true
