name: "${project.name}"
version: "${project.version}"
author: "MEFRREEX"
api: ["1.0.0"]
main: com.mefrreex.chatsplitter.ChatSplitter

permissions:
  chatsplitter.chat.local:
    default: op
  chatsplitter.chat.global:
    default: op
  chatsplitter.command.spy:
    default: op
